name: Hello World Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions!"
